feat: Support Power processor architecture for CP4I deployment
Signed-off-by: Denilson Nastacio <dnastaci@us.ibm.com>

diff --git a/config/argocd-cloudpaks/cp4i/templates/0050-presync-adjust-app-config.yaml b/config/argocd-cloudpaks/cp4i/templates/0050-presync-adjust-app-config.yaml
--- a/config/argocd-cloudpaks/cp4i/templates/0050-presync-adjust-app-config.yaml
+++ b/config/argocd-cloudpaks/cp4i/templates/0050-presync-adjust-app-config.yaml
@@ -5,14 +5,14 @@ metadata:
   annotations:
     argocd.argoproj.io/hook: PreSync
     argocd.argoproj.io/sync-wave: "50"
-  name: presync-cp4i-storage-classes
+  name: presync-cp4i-config
   namespace: {{.Values.metadata.argocd_namespace}}
 spec:
   template:
     spec:
       containers:
         - name: config
-          image: quay.io/openshift/origin-cli:latest
+          image: registry.redhat.io/openshift4/ose-cli:latest
           imagePullPolicy: IfNotPresent
           env:
             - name: ARGOCD_APP_NAME
@@ -45,15 +45,35 @@ spec:
               argo_cmd="${HOME}/argocd"
               result=0
 
+              linux_arch=$(uname -p)
+              argocd_cli_arch=amd64
+              if [ "${linux_arch}" == "ppc64le" ] || [ "${linux_arch}" == "s390x" ]; then
+                  argocd_cli_arch=${linux_arch}
+              fi
+
               argo_url=$(oc get route ${argo_route} -n ${ARGOCD_NAMESPACE} -ojsonpath='{.spec.host}') \
-              && curl -skL "${argo_url}/download/argocd-linux-amd64" -o "${argo_cmd}" \
-              && chmod 755 "${argo_cmd}" \
+              && cli_status=$(curl -skL "${argo_url}/download/argocd-linux-${argocd_cli_arch}" \
+                  -o "${argo_cmd}" \
+                  -w "%{http_code}") \
+              || result=1
+
+              if [ "${cli_status}" != "200" ]; then
+                  echo "ERROR: Unable to download argocd client."
+                  exit 2
+              fi
+
+              chmod 755 "${argo_cmd}" \
               && argo_pwd=$(oc get secret ${argo_secret} -n ${ARGOCD_NAMESPACE} -ojsonpath='{.data.admin\.password}' | base64 -d ; echo ) \
               && "${argo_cmd}" login "${argo_url}" --username admin --password "${argo_pwd}" --insecure \
               && "${argo_cmd}" app set "${ARGOCD_APP_NAME}" \
                   --helm-set-string storageclass.rwo="${storage_class_rwo}" \
                   --helm-set-string storageclass.rwx="${storage_class_rwx}" \
               && echo "INFO: ${ARGOCD_APP_NAME} successfully updated storage classes." \
+              && if [ "${linux_arch}" == "ppc64le" ]; then
+                     "${argo_cmd}" app set "${ARGOCD_APP_NAME}" \
+                         --helm-set-string modules.apic="false"
+                 fi \
+              && echo "INFO: ${ARGOCD_APP_NAME} successfully updated modules." \
               || result=1
 
               echo "INFO: Application ${ARGOCD_APP_NAME} current parameters:"
