chore: AIOps 3.2

diff --git a/config/argocd-cloudpaks/cp-shared/templates/00-presync-common-config-map.yaml b/config/argocd-cloudpaks/cp-shared/templates/00-presync-common-config-map.yaml
--- a/config/argocd-cloudpaks/cp-shared/templates/00-presync-common-config-map.yaml
+++ b/config/argocd-cloudpaks/cp-shared/templates/00-presync-common-config-map.yaml
@@ -2,7 +2,7 @@
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: common-config-map
+  name: pre-common-config-map
   annotations:
     argocd.argoproj.io/hook: PreSync
   namespace: openshift-gitops
@@ -31,6 +31,12 @@ spec:
               set -x
               api_url=$(oc get Infrastructure cluster  -o jsonpath={.status.apiServerURL})
 
+              ocp_domain=$(oc get ingress.config.openshift.io cluster -o jsonpath={.spec.domain})
+              if [ -z "${ocp_domain}" ]; then
+                  echo "ERROR: Unable to determine cluster domain."
+                  exit 1
+              fi
+
               storage_class_rwo=""
               storage_class_rwx=""
               if [[ "${api_url}" == *fyre.ibm.com* ]]; then
@@ -39,8 +45,24 @@ spec:
               else
                   platform=$(oc get Infrastructure cluster  -o jsonpath={.status.platform})
                   if [ "${platform}" == "AWS" ]; then
-                      storage_class_rwo="{{.Values.storageclass.rwo.aws}}"
-                      storage_class_rwx="{{.Values.storageclass.rwx.aws}}"
+                      ebs=$(oc get StorageClasses | grep kubernetes.io/aws-ebs | cut -d " " -f 1)
+                      efs=$(oc get StorageClasses | grep openshift.org/aws-efs | cut -d " " -f 1)
+                      if [ -n "${ebs}" ] && [ -n "${efs}" ]; then
+                          storage_class_rwo="${ebs}"
+                          storage_class_rwx="${efs}"
+                      else
+                          storage_class_rwo="{{.Values.storageclass.rwo.aws}}"
+                          storage_class_rwx="{{.Values.storageclass.rwx.aws}}"
+                      fi
+                  elif [ "${platform}" == "Azure" ]; then
+                      if oc get StorageClass azure-file 2> /dev/null &&
+                         oc get StorageClass managed-premium 2> /dev/null; then
+                          storage_class_rwo=managed-premium
+                          storage_class_rwx=azure-file
+                      else
+                          storage_class_rwo="{{.Values.storageclass.rwo.azure}}"
+                          storage_class_rwx="{{.Values.storageclass.rwx.azure}}"
+                      fi
                   elif [ "${platform}" == "IBMCloud" ]; then
                     vpc_class=$(oc get StorageClass | grep -c "ibmc-vpc" || result=0)
                     if [ ${vpc_class} -gt 0 ]; then
@@ -65,9 +87,10 @@ spec:
                   oc get configmap "${config_map_name}" \
                       --namespace "${ARGOCD_NAMESPACE}" > /dev/null 2>&1 \
                   && oc patch configmap "${config_map_name}" \
-                      --patch "{\"data\":{\"serviceaccount.argocd_application_controller\":\"{{.Values.serviceaccount.argocd_application_controller}}\", \"storageclass.rwo\":\"${storage_class_rwo}\", \"storageclass.rwx\":\"${storage_class_rwx}\" }}" \
+                      --patch "{\"data\":{\"cluster_domain\":\"${ocp_domain}\",\"serviceaccount.argocd_application_controller\":\"{{.Values.serviceaccount.argocd_application_controller}}\", \"storageclass.rwo\":\"${storage_class_rwo}\", \"storageclass.rwx\":\"${storage_class_rwx}\" }}" \
                       --namespace "${ARGOCD_NAMESPACE}" \
                   || oc create configmap "${config_map_name}" \
+                      --from-literal=cluster_domain="${ocp_domain}" \
                       --from-literal=serviceaccount.argocd_application_controller="{{.Values.serviceaccount.argocd_application_controller}}" \
                       --from-literal=storageclass.rwo="${storage_class_rwo}" \
                       --from-literal=storageclass.rwx="${storage_class_rwx}" \
