chore: AIOps 3.2 (#61)

diff --git a/config/cloudpaks/cp4aiops/resources/templates/evt-manager/99-postsync-check-evt-group.yaml b/config/cloudpaks/cp4aiops/resources/templates/evt-manager/99-postsync-check-evt-group.yaml
--- a/config/cloudpaks/cp4aiops/resources/templates/evt-manager/99-postsync-check-evt-group.yaml
+++ b/config/cloudpaks/cp4aiops/resources/templates/evt-manager/99-postsync-check-evt-group.yaml
@@ -1,9 +1,9 @@
-# Ensuring all CSVs across all namespaces are ready
+# https://www.ibm.com/docs/en/cloud-paks/cp-waiops/3.1.1?topic=installing-postinstallation-tasks
 ---
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: check-cp4i-csvs
+  name: post-check-evt-group
   annotations:
     argocd.argoproj.io/hook: PostSync
   namespace: openshift-gitops
@@ -23,7 +23,7 @@ spec:
               cpu: "300m"
           env:
             - name: TARGET_NAMESPACE
-              value: "{{.Values.argocd_app_namespace}}"
+              value: "{{.Values.metadata.argocd_app_namespace}}-evt"
           command:
             - /bin/sh
             - -c
@@ -34,31 +34,28 @@ spec:
               result=0
 
               current_seconds=0
-              operation_limit_seconds=$(( $(date +%s) + 2400 ))
-              csv_installing=0
+              operation_limit_seconds=$(( $(date +%s) + 7200 ))
+              cem_formation_status=""
               while [ ${current_seconds} -lt ${operation_limit_seconds} ]; do
-                if [ $(oc get csv -n "${TARGET_NAMESPACE}" | grep -vc Succeeded) -gt 1 ] || \
-                   [ $(oc get csv -n ibm-common-services | grep -vc Succeeded) -gt 1 ]; then
-                  csv_installing=1
-                  echo "INFO: CSVs still installing."
-                  sleep 60
-                else
-                  csv_installing=0
-                  break
+                cem_formation_status=$(oc get cemformation evtmanager -n "${TARGET_NAMESPACE}" -o jsonpath='{.status.phase}')
+                if [ "${cem_formation_status}" == "ERROR" ] \
+                  || [ "${cem_formation_status}" == "OK" ]; then
+                   break
                 fi
+                echo "INFO: cemformation not found, waiting some more."
+                sleep 30
+
                 current_seconds=$(( $(date +%s) ))
               done
 
-              oc get csv -n "${TARGET_NAMESPACE}"
-              oc get csv -n ibm-common-services
-
-              if [ ${csv_installing} -eq 0 ]; then
-                echo "INFO: All CSVs are ready."
+              if [ "${cem_formation_status}" == "Error" ]; then
+                echo "INFO: CEM Formation phase is not OK: ${cem_formation_status}"
+                result=1
               else
-                echo "ERROR: CSVs still not ready."
-                oc get csv -A | grep -v Succeeded
-                exit 1
+                echo "INFO: CEM Formation phase is OK."
               fi
+
+              exit "${result}"
 
       restartPolicy: Never
       serviceAccountName: {{.Values.serviceaccount.argocd_application_controller}}
