feat: Upgrade CP4D to 4.8.0
Signed-off-by: Denilson Nastacio <dnastaci@us.ibm.com>

diff --git a/config/cloudpaks/cp4d/templates/0090-sync-cluster-setup.yaml b/config/cloudpaks/cp4d/templates/0090-sync-cluster-setup.yaml
--- a/config/cloudpaks/cp4d/templates/0090-sync-cluster-setup.yaml
+++ b/config/cloudpaks/cp4d/templates/0090-sync-cluster-setup.yaml
@@ -1,5 +1,5 @@
 ---
-# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.7.x?topic=information-setting-up-installation-environment-variables
+# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=information-setting-up-installation-environment-variables
 apiVersion: batch/v1
 kind: Job
 metadata:
@@ -13,7 +13,6 @@ spec:
     spec:
       containers:
         - name: configure-cluster
-          # Image associated with CPD CLI v13.0.1 @ https://github.com/IBM/cpd-cli/releases/tag/v13.0.1
           image: "icr.io/cpopen/cpd/olm-utils-v2:{{.Values.version}}"
           env:
             - name: PROJECT_CERT_MANAGER
@@ -21,7 +20,7 @@ spec:
             - name: PROJECT_LICENSE_SERVICE
               value: ibm-licensing
             - name: PROJECT_SCHEDULING_SERVICE
-              value: cpd-scheduler
+              value: ibm-cpd-scheduler
             - name: VERSION
               value: {{.Values.version}}
             - name: COMPONENTS
@@ -35,9 +34,17 @@ spec:
               set -eo pipefail
               set -x
 
+              export KUBECONFIG=/tmp/kubeconfig
+              api_url=$(oc get Infrastructure cluster -o jsonpath='{.status.apiServerURL}')
+              oc login "${api_url}" --token="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" --insecure-skip-tls-verify \
+              || {
+                  echo "WARNING: Unable to login to the cluster."
+                  exit 1
+              }
+
               result=0
 
-              # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.7.x?topic=cluster-installing-shared-components
+              # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=cluster-installing-shared-components
               bin/apply-cluster-components \
                   --release=${VERSION:?} \
                   --license_acceptance=true \
@@ -52,109 +59,32 @@ spec:
               || result=1
 
               if [[ ${COMPONENTS:?} =~ cognos_analytics ]] \
-                  || [[ ${COMPONENTS} =~ dv ]] \
                   || [[ ${COMPONENTS} =~ db2 ]] \
                   || [[ ${COMPONENTS} =~ bigsql ]] \
                   || [[ ${COMPONENTS} =~ watson_discovery ]] \
                   || [[ ${COMPONENTS} =~ wkc ]] \
                   || [[ ${COMPONENTS} =~ ws ]] \
                   || [[ ${COMPONENTS} =~ wml_accelerator ]]; then
-                  echo "INFO: Must update CRI-O container settings depending on the target env."
+                  echo "INFO: Must update process IDs limit settings depending on the target env."
               else
-                  echo "INFO: None of the components to be installed require crio-changes"
+                  echo "INFO: None of the components to be installed require process IDs limit changes"
                   exit 0
               fi
 
-              OPENSHIFT_TYPE=self-managed
-              platform=$(oc get Infrastructure cluster  -o jsonpath={.status.platform})
-              case "${platform}" in
-                  Azure)
-                      oc get Infrastructure cluster -o jsonpath={.status.platformStatus} \
-                          | grep red-hat-managed \
-                      && OPENSHIFT_TYPE=aro
-                      ;;
-                  AWS)
-                      oc get Infrastructure cluster -o jsonpath={.status.platformStatus} \
-                          | grep red-hat-managed \
-                      && OPENSHIFT_TYPE=rosa
-                      ;;
-                  IBMCloud)
-                      OPENSHIFT_TYPE=roks
-                      ;;
-                  *)
-                      OPENSHIFT_TYPE=self-managed
-              esac
-
-              ocp_version=$(oc get ClusterVersion version -o jsonpath='{.status.desired.version}' | cut -d "." -f 1,2)
-              if [ -z "${ocp_version}" ]; then
-                  echo "ERROR: Unable to determine cluster version for ${cluster_name}"
-                  exit 1
-              fi
-
-              hypershift_deployment=$(oc get Infrastructure cluster \
-                -o jsonpath='{.metadata.labels.hypershift\.openshift\.io/managed}')
-
-              # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.7.x?topic=settings-changing-cri-o-container
-              crio="none"
-              if [ -n "${hypershift_deployment}" ]; then
-                  crio="none"
-              elif [ "${OPENSHIFT_TYPE}" == "roks" ]; then
-                  crio="none"
-              elif [ "${platform}" == "Azure" ]; then
-                  crio="azure"
-              elif [ "${OPENSHIFT_TYPE}" == "self-managed" ] && [ "${ocp_version}" == "4.10" ]; then
-                  crio="pid"
-              elif [ "${OPENSHIFT_TYPE}" == "self-managed" ] && [ "${ocp_version}" == "4.12" ]; then
-                  crio="kubelet"
-              fi
-
-              if [ "${crio}" == "pid" ]; then
-                  echo "INFO: Changing CRI-O container settings"
-                  bin/apply-crio --openshift-type=${OPENSHIFT_TYPE} \
-                  || result=1
-              elif [ "${crio}" == "kubelet" ]; then
-                  oc label machineconfigpool worker custom-crio=pid-limit --overwrite \
-                  && oc apply -f - << EOF
+              # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=settings-changing-process-ids-limit
+              oc apply -f - << EOF
               apiVersion: machineconfiguration.openshift.io/v1
               kind: KubeletConfig
               metadata:
-                name: cpd-crio-kubeletconfig
+                name: cpd-pidslimit-kubeletconfig
               spec:
                 kubeletConfig:
                   podPidsLimit: 16384
-                machineConfigPoolSelector:
-                  matchLabels:
-                    custom-crio: pid-limit
-              EOF
-                  oc get kubeletconfig.machineconfiguration.openshift.io/cpd-crio-kubeletconfig -o yaml
-
-                  oc wait kubeletconfig.machineconfiguration.openshift.io/cpd-crio-kubeletconfig \
-                      --for=condition=Success=true \
-                      --timeout=20s \
-                  || result=1
-              elif [ "${crio}" == "azure" ]; then
-                  oc apply -f - << EOF
-              apiVersion: machineconfiguration.openshift.io/v1
-              kind: ContainerRuntimeConfig
-              metadata:
-                name: new-large-pidlimit
-              spec:
-                containerRuntimeConfig:
-                  pidsLimit: 16384
                 machineConfigPoolSelector:
                   matchExpressions:
                   - key: pools.operator.machineconfiguration.openshift.io/worker
                     operator: Exists
               EOF
-                  oc get no -o name \
-                      | grep compute \
-                      | awk '{system("oc debug " $1 " -- bash -lc \"chroot /host sudo crio-status config | grep pids_limit\" ")}'
-
-                  oc wait ContainerRuntimeConfig.machineconfiguration.openshift.io/new-large-pidlimit \
-                      --for=condition=Success=true \
-                      --timeout=20s \
-                  || result=1
-              fi
 
               # Not attempting to set the IBM entitlement key because it is
               # already a prerequisite for this repository.
diff --git a/config/cloudpaks/cp4d/templates/0100-sync-install-olm.yaml b/config/cloudpaks/cp4d/templates/0100-sync-install-olm.yaml
--- a/config/cloudpaks/cp4d/templates/0100-sync-install-olm.yaml
+++ b/config/cloudpaks/cp4d/templates/0100-sync-install-olm.yaml
@@ -1,5 +1,5 @@
 ---
-# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.7.x?topic=installing
+# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=installing
 apiVersion: batch/v1
 kind: Job
 metadata:
@@ -20,6 +20,8 @@ spec:
               value: {{.Values.metadata.operators_namespace}}
             - name: PROJECT_CPD_INST_OPERANDS
               value: {{.Values.metadata.operands_namespace}}
+            - name: STG_CLASS_BLOCK
+              value: {{.Values.storageclass.rwo}}
             - name: VERSION
               value: {{.Values.version}}
             - name: COMPONENTS
@@ -35,7 +37,15 @@ spec:
 
               result=0
 
-              # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.7.x?topic=services-creating-informix-scc
+              export KUBECONFIG=/tmp/kubeconfig
+              api_url=$(oc get Infrastructure cluster -o jsonpath='{.status.apiServerURL}')
+              oc login "${api_url}" --token="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" --insecure-skip-tls-verify \
+              || {
+                  echo "WARNING: Unable to login to the cluster."
+                  exit 1
+              }
+
+              # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=services-creating-informix-scc
               echo "INFO: Creating custom security context constraints for services."
               if [[ ${COMPONENTS} =~ informix ]]; then
                   bin/apply-scc \
@@ -47,7 +57,7 @@ spec:
                   }
               fi
 
-              # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.7.x?topic=data-installing-cloud-pak-foundational-services
+              # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-installing-cloud-pak-foundational-services
               echo "INFO: Installing foundational services" \
               && bin/authorize-instance-topology \
                   --cpd_operator_ns=${PROJECT_CPD_INST_OPERATORS:?} \
@@ -57,6 +67,7 @@ spec:
                   --cpd_operator_ns=${PROJECT_CPD_INST_OPERATORS:?} \
                   --cpd_instance_ns=${PROJECT_CPD_INST_OPERANDS:?} \
                   --license_acceptance=true \
+                  --block_storage_class=${STG_CLASS_BLOCK} \
               && bin/get-license \
                   --release=${VERSION} \
                   --license-type=SE \
@@ -67,7 +78,7 @@ spec:
                   --cpd_operator_ns=${PROJECT_CPD_INST_OPERATORS} \
               || result=1
 
-              # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.7.x?topic=data-specifying-privileges-that-db2u-runs
+              # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-specifying-privileges-that-db2u-runs
               oc apply -f - <<EOF
               apiVersion: v1
               data:
